version: '3.8'

services:
  backend:
    build:
      context: ./docker/backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=app
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db
  web:
    image: nginx:stable-alpine
    container_name: web
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

volumes:
  db: